apiVersion: batch/v1
kind: Job
metadata:
  name: mattermost-post-job-success
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
        - name: mattermost-success
          image: mattermost-api:v1
          command: [ "python3", "mattermost.py"]
          env:
          - name: message
            value: "MESSAGE FROM ARGOCD: The last sync is:  *** Sync OK ***"
          - name: url
            value: "mattermost.local"
          - name: token
            value: "nshwfrtm6jnktf7wxk5tbigw9o"
          - name: scheme
            value: "http"
          - name: port
            value: "8065"
          - name: channel_name
            value: "sync-phases-demo"
          - name: team_name
            value: "Argo-Course"
      restartPolicy: Never
  backoffLimit: 0
